<a href="https://colab.research.google.com/github/sofianna-e/DeliveriesEKPA/blob/main/%20phishing_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/refs/heads/main/Data/phishing_dataset.csv', delimiter=',')

In [21]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  \
0                    codepen.io        0        0           1          3   
1  muggetlogin.oa.r.appspot.com        0        0           0          1   
2                thenextweb.com        0        0           1          6   
3                 webfiddle.net        0        0           1          4   
4                   twitter.com        0        0           1          1   

   Redirection  https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  \
0            0             0        0              0           0            1   
1            0             0        1              0           1            1   
2            0             0        0              0           0            1   
3            0             0        0              0           0            1   
4            0             0        0              0           0            1   

   Domain_Age  Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  \
0           0           1       0           0            1             0   
1           1           1       0           0            1             0   
2           0           0       0           0            1             0   
3           0           1       0           0            1             0   
4           1           1       0           0            1             0   

   Label  
0      0  
1      1  
2      0  
3      1  
4      0

In [22]:
X = data.drop(['Domain', 'Label'], axis=1)

In [23]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           1          3            0             0   
1        0        0           0          1            0             0   
2        0        0           1          6            0             0   
3        0        0           1          4            0             0   
4        0        0           1          1            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              0           0            1           0           1   
1        1              0           1            1           1           1   
2        0              0           0            1           0           0   
3        0              0           0            1           0           1   
4        0              0           0            1           1           1   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       0           0            1             0  
1       0           0            1             0  
2       0           0            1             0  
3       0           0            1             0  
4       0           0            1             0

In [24]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [26]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [27]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [28]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.7983333333333333
Precision: 0.8216909435279209
Recall: 0.7983333333333333
F1 Score: 0.7941241279616137
Confusion Matrix:
[[1422   98]
 [ 507  973]]

SVC Metrics:
Accuracy: 0.8276666666666667
Precision: 0.8600803018615641
Recall: 0.8276666666666667
F1 Score: 0.823271640247083
Confusion Matrix:
[[1488   32]
 [ 485  995]]

RandomForestClassifier Metrics:
Accuracy: 0.8596666666666667
Precision: 0.8702655797029762
Recall: 0.8596666666666667
F1 Score: 0.858464719381323
Confusion Matrix:
[[1438   82]
 [ 339 1141]]


/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(



MLPClassifier Metrics:
Accuracy: 0.8523333333333334
Precision: 0.8671978237637228
Recall: 0.8523333333333334
F1 Score: 0.8505837253229517
Confusion Matrix:
[[1451   69]
 [ 374 1106]]

KNeighborsClassifier Metrics:
Accuracy: 0.7903333333333333
Precision: 0.7904777244778516
Recall: 0.7903333333333333
F1 Score: 0.7903415104868822
Confusion Matrix:
[[1192  328]
 [ 301 1179]]

DecisionTreeClassifier Metrics:
Accuracy: 0.8586666666666667
Precision: 0.8700244195964341
Recall: 0.8586666666666667
F1 Score: 0.8573750095998771
Confusion Matrix:
[[1441   79]
 [ 345 1135]]


In [29]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
2  RandomForestClassifier  0.859667   0.870266  0.859667  0.858465
5  DecisionTreeClassifier  0.858667   0.870024  0.858667  0.857375
3           MLPClassifier  0.852333   0.867198  0.852333  0.850584
1                     SVC  0.827667   0.860080  0.827667  0.823272
0      LogisticRegression  0.798333   0.821691  0.798333  0.794124
4    KNeighborsClassifier  0.790333   0.790478  0.790333  0.790342


In [30]:
#creating repositories to store model performance results
ML_Model = []
acc_train = []
acc_test = []

In [31]:
#function call to save the results
def storeResults(model, a,b):
  ML_Model.append(model)
  acc_train.append(round(a, 3))
  acc_test.append(round(b, 3))

In [33]:
# Creating dataframe
results = pd.DataFrame({ 'ML Model': ML_Model,
    'Train Accuracy': acc_train,
    'Test Accuracy': acc_test})
results

Empty DataFrame
Columns: [ML Model, Train Accuracy, Test Accuracy]
Index: []

In [34]:
#classification of the dataframe based on the accuracy of the models
results.sort_values(by=['Test Accuracy', 'Train Accuracy'], ascending=False)

Empty DataFrame
Columns: [ML Model, Train Accuracy, Test Accuracy]
Index: []