<a href="https://colab.research.google.com/github/sofianna-e/DeliveriesEKPA/blob/main/Phishing_database_exercise%20delivery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/refs/heads/main/Data/phishing_dataset.csv', delimiter=',')

In [21]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  \
0                    codepen.io        0        0           1          3   
1  muggetlogin.oa.r.appspot.com        0        0           0          1   
2                thenextweb.com        0        0           1          6   
3                 webfiddle.net        0        0           1          4   
4                   twitter.com        0        0           1          1   

   Redirection  https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  \
0            0             0        0              0           0            1   
1            0             0        1              0           1            1   
2            0             0        0              0           0            1   
3            0             0        0              0           0            1   
4            0             0        0              0           0            1   

   Domain_Age  Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  \
0           0           1       0           0            1             0   
1           1           1       0           0            1             0   
2           0           0       0           0            1             0   
3           0           1       0           0            1             0   
4           1           1       0           0            1             0   

   Label  
0      0  
1      1  
2      0  
3      1  
4      0

In [22]:
X = data.drop(['Domain', 'Label'], axis=1)

In [23]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           1          3            0             0   
1        0        0           0          1            0             0   
2        0        0           1          6            0             0   
3        0        0           1          4            0             0   
4        0        0           1          1            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              0           0            1           0           1   
1        1              0           1            1           1           1   
2        0              0           0            1           0           0   
3        0              0           0            1           0           1   
4        0              0           0            1           1           1   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       0           0            1             0  
1       0           0            1             0  
2       0           0            1             0  
3       0           0            1             0  
4       0           0            1             0

In [24]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [26]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [27]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [28]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.7983333333333333
Precision: 0.8216909435279209
Recall: 0.7983333333333333
F1 Score: 0.7941241279616137
Confusion Matrix:
[[1422   98]
 [ 507  973]]

SVC Metrics:
Accuracy: 0.8276666666666667
Precision: 0.8600803018615641
Recall: 0.8276666666666667
F1 Score: 0.823271640247083
Confusion Matrix:
[[1488   32]
 [ 485  995]]

RandomForestClassifier Metrics:
Accuracy: 0.8596666666666667
Precision: 0.8702655797029762
Recall: 0.8596666666666667
F1 Score: 0.858464719381323
Confusion Matrix:
[[1438   82]
 [ 339 1141]]


/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(



MLPClassifier Metrics:
Accuracy: 0.8523333333333334
Precision: 0.8671978237637228
Recall: 0.8523333333333334
F1 Score: 0.8505837253229517
Confusion Matrix:
[[1451   69]
 [ 374 1106]]

KNeighborsClassifier Metrics:
Accuracy: 0.7903333333333333
Precision: 0.7904777244778516
Recall: 0.7903333333333333
F1 Score: 0.7903415104868822
Confusion Matrix:
[[1192  328]
 [ 301 1179]]

DecisionTreeClassifier Metrics:
Accuracy: 0.8586666666666667
Precision: 0.8700244195964341
Recall: 0.8586666666666667
F1 Score: 0.8573750095998771
Confusion Matrix:
[[1441   79]
 [ 345 1135]]


In [29]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
2  RandomForestClassifier  0.859667   0.870266  0.859667  0.858465
5  DecisionTreeClassifier  0.858667   0.870024  0.858667  0.857375
3           MLPClassifier  0.852333   0.867198  0.852333  0.850584
1                     SVC  0.827667   0.860080  0.827667  0.823272
0      LogisticRegression  0.798333   0.821691  0.798333  0.794124
4    KNeighborsClassifier  0.790333   0.790478  0.790333  0.790342


In [37]:
#creating repositories to store model performance results
ML_Model = []
acc_train = []
acc_test = []

#function call to save the results
def storeResults(model, a,b):
  ML_Model.append(model)
  acc_train.append(round(a, 3))
  acc_test.append(round(b, 3))

In [40]:
#Decision Tree Algorithm
from sklearn.tree import DecisionTreeClassifier

#model presentation
tree = DecisionTreeClassifier(max_depth = 5)
#model suitability check
tree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5)

In [41]:

#prediction of the target price from the model
y_test_tree = tree.predict(X_test)
y_train_tree = tree.predict(X_train)


In [42]:
#assessment of model accuracy
acc_train_tree = accuracy_score(y_train,y_train_tree)
acc_test_tree = accuracy_score(y_test,y_test_tree)

print("Decision Tree: Accuracy on training Data: {:.3f}".format(acc_train_tree))
print("Decision Tree: Accuracy on test Data: {:.3f}".format(acc_test_tree))

Decision Tree: Accuracy on training Data: 0.813
Decision Tree: Accuracy on test Data: 0.814


In [43]:
#save results
storeResults('Decision Tree', acc_train_tree, acc_test_tree)

In [44]:
# Random Forest Algorithm
from sklearn.ensemble import RandomForestClassifier

#model presentation
forest = RandomForestClassifier(max_depth=5)

#model suitability check
forest.fit(X_train, y_train)


RandomForestClassifier(max_depth=5)

In [45]:

#prediction of the target price from the model
y_test_forest = forest.predict(X_test)
y_train_forest = forest.predict(X_train)

In [46]:
#assessment of model accuracy
acc_train_forest = accuracy_score(y_train,y_train_forest)
acc_test_forest = accuracy_score(y_test,y_test_forest)

print("Random forest: Accuracy on training Data: {:.3f}".format(acc_train_forest))
print("Random forest: Accuracy on test Data: {:.3f}".format(acc_test_forest))

Random forest: Accuracy on training Data: 0.817
Random forest: Accuracy on test Data: 0.818


In [47]:

#save results
storeResults('Random Forest', acc_train_forest, acc_test_forest)


In [48]:
#Support vector machine algorithm
from sklearn.svm import SVC

#model presentation
svm = SVC(kernel='linear', C=1.0, random_state=12)
#model suitability check
svm.fit(X_train, y_train)

SVC(kernel='linear', random_state=12)

In [49]:

#prediction of the target price from the model
y_test_svm = svm.predict(X_test)
y_train_svm = svm.predict(X_train)

In [50]:
#calculation of model accuracy
acc_train_svm = accuracy_score(y_train,y_train_svm)
acc_test_svm = accuracy_score(y_test,y_test_svm)

print("SVM: Accuracy on training Data: {:.3f}".format(acc_train_svm))
print("SVM : Accuracy on test Data: {:.3f}".format(acc_test_svm))

SVM: Accuracy on training Data: 0.802
SVM : Accuracy on test Data: 0.803


In [51]:

#save results
storeResults('SVM', acc_train_svm, acc_test_svm)

In [52]:
# Multilayer Perceptrons Algorithm
from sklearn.neural_network import MLPClassifier

#model presentation
mlp = MLPClassifier(alpha=0.001, hidden_layer_sizes=([100,100,100]))

#model suitability check
mlp.fit(X_train, y_train)

MLPClassifier(alpha=0.001, hidden_layer_sizes=[100, 100, 100])

In [53]:
#prediction of the target price from the model
y_test_mlp = mlp.predict(X_test)
y_train_mlp = mlp.predict(X_train)

In [54]:

#calculation of model accuracy
acc_train_mlp = accuracy_score(y_train,y_train_mlp)
acc_test_mlp = accuracy_score(y_test,y_test_mlp)

print("Multilayer Perceptrons: Accuracy on training Data: {:.3f}".format(acc_train_mlp))
print("Multilayer Perceptrons: Accuracy on test Data: {:.3f}".format(acc_test_mlp))


Multilayer Perceptrons: Accuracy on training Data: 0.867
Multilayer Perceptrons: Accuracy on test Data: 0.860


In [55]:

#save results
storeResults('Multilayer Perceptrons', acc_train_mlp, acc_test_mlp)

In [56]:
# Creating dataframe
results = pd.DataFrame({ 'ML Model': ML_Model,
    'Train Accuracy': acc_train,
    'Test Accuracy': acc_test})
results

ML Model  Train Accuracy  Test Accuracy
0           Decision Tree           0.813          0.814
1           Random Forest           0.817          0.818
2                     SVM           0.802          0.803
3  Multilayer Perceptrons           0.867          0.860

In [57]:
#classification of the dataframe based on the accuracy of the models
results.sort_values(by=['Test Accuracy', 'Train Accuracy'], ascending=False)

ML Model  Train Accuracy  Test Accuracy
3  Multilayer Perceptrons           0.867          0.860
1           Random Forest           0.817          0.818
0           Decision Tree           0.813          0.814
2                     SVM           0.802          0.803